[package]
name = "bitcask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "bitcask"
path = "src/lib.rs"

[dependencies]
parking_lot = "0.12.1"
thiserror = "1.0.39"
log = "0.4.0"
env_logger = "0.9.0"